name: corrosion-drift
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - pytorch
  - torchvision
  - pip
  - pip:
      - tqdm
      - imbalanced-learn
      - openpyxl
